### ISSUE TITLE
Document on why supabase

### ISSUE THREAD

**Issue by mboyamike** [KenyaFlutterDev/flutter_ke#10]
We should document on why we chose to use a backend as a service, and why we chose supabase specifically

**Comment by mauricenyanja** [comment]
I can aid in why supabase actually

1.SQL ,Postgress
2. It charges for storage
3. Has a dashboard

**Comment by mauricenyanja** [comment]
So what do U @mboyamike think should I create a PR with supabase on reasons why?

**Comment by mboyamike** [comment]
Yes please

It'll be especially helpful having it in the README.md

**Comment by mboyamike** [comment]
Also a few more things to add

You can specify how it's fully open source and helps avoid vendor lock-in if we need to later move to our own server
